# This workflow will install Python dependencies and run tests with Python 3.8

name: emotion - pr

on: pull_request

permissions: read-all

jobs:
  PreJobs:
    runs-on: ubuntu-latest
    name: Check versions and syntax
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: pip install toml gitpython autoflake

    - name: Run Checks
      run: python .github/workflows/checks.py


  buildAndTests:
    runs-on: ubuntu-latest
    name: Build and Tests
    needs: PreJobs
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install Poetry
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.0b1 python3.8 - --yes

        poetry=$HOME/.local/bin/poetry
        
        $poetry config virtualenvs.in-project true

    - name: Cache project's modules
      uses: actions/cache@v3
      env:
        cache-name: cache-project-modules
      with:
        # Cache files that are stored in `~/.venv`
        path: ./.venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}

    - name: Build Project
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        poetry=$HOME/.local/bin/poetry

        echo "Checking that the poetry.lock file corresponds to the current version of pyproject.toml."
        $poetry lock --check

        $poetry install --no-interaction

    - name: Test with pytest
      run: |
        export PATH="$(pwd)/.venv/bin:$PATH"
        dvc pull data/raw_sample
        pytest tests
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.DVCSTORAGE }}
