# This workflow will validate metadata + syntax, install Python dependencies and run tests with Python 3.8

name: emotion - push

on:
  push:
    branches-ignore:
      - "main"

permissions: read-all

jobs:
  buildAndTests:
    runs-on: ubuntu-latest
    name: Build and Tests
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install Poetry
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.1.14 python3.8 - --yes

        poetry=$HOME/.local/bin/poetry
        
        $poetry config virtualenvs.in-project true

    - name: Cache project's modules
      uses: actions/cache@v3
      env:
        cache-name: cache-project-modules
      with:
        # Cache files that are stored in `~/.venv`
        path: ./.venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}

    - name: Build Project
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        sudo apt-get install libsndfile1

        poetry=$HOME/.local/bin/poetry

        $poetry install --no-interaction --without dev
        ./.venv/bin/pip install pytest

    - name: Test with pytest
      run: |
        export PATH="$(pwd)/.venv/bin:$PATH"
        dvc pull data/raw_sample
        dvc pull emotion/artifacts.dvc
        pytest tests
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.DVCSTORAGE }}
